# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Опционально: можно добавить параметры (входные данные)
    inputs:
      environment:
        description: 'Environment 2026 to run'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello G N!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo второй скрипт
          
      # Пытаемся скачать лог из самого последнего успешного запуска
      - name: Download previous artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: blank1.yml         # точное имя файла этого workflow )
          name: deployment-log       # Имя скачиваемого артефакта
          path: .                    # Скачиваем в текущую папку
          if_error_continue: true    # Если это самый первый запуск и артефакта еще нет — не прерывать сборку
 
      - name: show summary
        run: |
          export TZ="Europe/Moscow"
          CURRENT_TIME=$(date "+%Y-%m-%d %H:%M:%S")
          echo "скрипт удачно запущен!" >> $GITHUB_STEP_SUMMARY
          echo "14 августа 2026 года" >> $GITHUB_STEP_SUMMARY
          echo "Время запуска (UTC): **$CURRENT_TIME**" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "Запуск выполнен в: $CURRENT_TIME" >> log.txt
          
      # Загрузка файла log.txt в качестве артефакта GitHub Actions
      - name: Upload artifact log
        uses: actions/upload-artifact@v4
        with:
          name: deployment-log  # Имя скачиваемого архива на GitHub
          path: log.txt         # Путь к файлу, который мы сохраняем
          overwrite: true

